using System.Collections;
using UnityEngine;

namespace Yahtzee.Presentation
{
    /// <summary>Drives Oma's character animation: a gentle rotation of sitting idles
    /// (idle/shift/talking) plus one-shot reactions (clap for good scores, disbelief for
    /// bad ones). States are crossfaded by name — the AnimatorController is generated by
    /// the "Yahtzee/Setup Oma Assets" editor tool from the imported FBX clips.</summary>
    public sealed class OmaView : MonoBehaviour
    {
        public enum Reaction { Clap, Disbelief }

        private const string StateIdle = "Sitting Idle";
        private const string StateShift = "Sitting";
        private const string StateTalking = "Sitting Talking";
        private const string StateClap = "Sitting Clap";
        private const string StateDisbelief = "Sitting Disbelief";
        private const float Fade = 0.3f;

        private Animator _animator;
        private float _nextIdleChange;
        private bool _reacting;
        private System.Random _rng;

        public void Init(Animator animator)
        {
            _animator = animator;
            _animator.applyRootMotion = false; // she stays in her chair
            _rng = new System.Random(GetInstanceID());
            _nextIdleChange = Time.time + NextIdleDelay();
        }

        private void Update()
        {
            if (_animator == null || _reacting || Time.time < _nextIdleChange)
                return;
            // Mostly plain idle, with occasional shifts and chatty moments.
            double pick = _rng.NextDouble();
            string state = pick < 0.5 ? StateIdle : pick < 0.8 ? StateShift : StateTalking;
            _animator.CrossFadeInFixedTime(state, Fade);
            _nextIdleChange = Time.time + NextIdleDelay();
        }

        public void PlayReaction(Reaction reaction)
        {
            if (_animator == null)
                return;
            StopAllCoroutines();
            StartCoroutine(ReactionRoutine(reaction == Reaction.Clap ? StateClap : StateDisbelief));
        }

        private IEnumerator ReactionRoutine(string state)
        {
            _reacting = true;
            _animator.CrossFadeInFixedTime(state, Fade);
            yield return new WaitForSeconds(Fade + 0.05f);
            // Hold for the clip's own length, then ease back into idling.
            float length = _animator.GetCurrentAnimatorStateInfo(0).length;
            yield return new WaitForSeconds(Mathf.Max(0.5f, length - Fade));
            _animator.CrossFadeInFixedTime(StateIdle, Fade);
            _reacting = false;
            _nextIdleChange = Time.time + NextIdleDelay();
        }

        private float NextIdleDelay() => 5f + (float)(_rng.NextDouble() * 7.0); // 5-12 s
    }
}
